### ISSUE TITLE
XRay не обновляется

### ISSUE THREAD

**Issue by AndrewP-GH** [Skrill0/XKeen#1]
Установил пару недель назад xkeen на свой кинетик, все отлично работает, но xray не обновляется.

В релизах xray вижу версию выше, чем так, которая имеется сейчас https://github.com/XTLS/Xray-core/releases.

При попытке обновить пишет следующее:
```
(config)> exec sh
BusyBox v1.36.1 (2024-02-22 20:34:43 UTC) built-in shell (ash)

/ # xray --version
Xray 1.8.4 (Xray, Penetrates Everything.) Custom (go1.21.0 linux/arm64)
A unified platform for anti-censorship.
/ # xkeen -ux
  Проверка обновления Xray
  Нет доступных обновлений Xray
  ```

**Comment by AndrewP-GH** [comment]
В репозитории openwrt-xray версия тоже актуальная 1.8.23 (как и в core) https://github.com/yichya/openwrt-xray/releases

**Comment by jameszeroX** [comment]
> Xray 1.8.4

Версия ядра [зафиксирована](https://github.com/Skrill0/XKeen/releases/tag/1.1.3) намерено и автообновление отключено. Подробности смотрите на [форуме](https://forum.keenetic.com/topic/16899-xkeen/) Кинетика.
Вы можете вручную скачать необходимую версию в соответствии с архитектурой процессора и заменить в папке /opt/sbin/ роутера, если понимаете зачем это нужно.

**Comment by AndrewP-GH** [comment]
Не баг, а фича :) 
Понял, спасибо
