### ISSUE TITLE
Свободный 443 порт

### ISSUE THREAD

**Issue by jamesRUS52** [Skrill0/XKeen#5]
Добрый день!

Софт отличный, Спасибо

Поясните вот это требование по переносу служб keenetic на другой порт

```
/opt/etc/xray/configs # xkeen -restart
  Прокси-клиент остановлен

  Ошибка: 
  Порт 443 занят сервисами Keenetic
  Невозможно использовать TProxy не освободив порт
    
  Перейдите в CLI роутера   
  Стандартный адрес
      192.168.1.1/a
	  
  Перенесите сервисы на любой из следующих портов 
      5083 | 5443 | 8083 | 8443 | 65083
  
  Команда переноса
      ip http ssl port {port}
  
  Пример записи
      ip http ssl port 8443
	  
  Сохраните изменения
      system configuration save

```

ведь по факту на 443 после переноса все равно ничего не запускается

**Comment by sten30** [comment]
Человек просто завернул ssl https трафик с тысяч роутеров к себе. Весь трафик банковских приложений и прочее.
Уже вижу здесь все инструкции почистил. Уехал в Дубай видимо.

**Comment by jameszeroX** [comment]
> Поясните вот это требование по переносу служб keenetic на другой порт

Требуется для работы TProxy модуля. Подробнее тут https://forum.keenetic.ru/topic/17122-не-работает-tproxy-на-ipv4/

**Comment by Skrill0** [comment]
> Человек просто завернул ssl https трафик с тысяч роутеров к себе. Весь трафик банковских приложений и прочее. Уже вижу здесь все инструкции почистил. Уехал в Дубай видимо.


Доброго Вам дня.
Не желаете уточнить свой комментарий?)
